#!/bin/bash

. Load
echo

From=$(date -d "$(stat / | grep "Birth" | sed 's/Birth: //g')" +%s)
Now=$(date +%s)
Seconds=$(($Now-$From))
export SecondsInDay=$((60*60*24))
export SecondsInMonth=$(($SecondsInDay*30))
export Months=$(($Seconds/$SecondsInMonth))
export Days=$(( MonthSeconds=$Months*$SecondsInMonth, RemainingSeconds=$Seconds-MonthSeconds, RemainingSeconds/$SecondsInDay ))
if [[ $Months < 2 ]]; then
    Info "$Months months & $Days days"
    Divide
    Success "Everything is good. Happy coding!"
    Divide
elif [[ $Months > 1 ]] && [[ $Months < 3 ]]; then
    Info "$Months months & $Days days"
    Divide
    Warning "It's better to install everything again. But it's not a force. Do it in your free time."
    Divide
else [[ $Months > 2 ]];
    Info "$Months months & $Days days"
    Divide
    Error "It's absolutely necessary to install everything again. It's a force. Do it ASAP."
    Divide
fi
