#!/bin/bash

. Load

Extract

if [[ $Organization == "" ]]; then 
    Error 'Its not an organization path';
    exit;
fi

Target=$PWD
Parent=$(dirname $PWD);
BackupFilename=basename $PWD
BackupPath


sudo mkdir -p /Backup$Parent
sudo chmod -R 777 /Backup$Parent

# rsync -r --progress $Target /Backup$Target --exclude .git --exclude bin --exclude obj --exclude node_modules
zip -r $Filename.zip
