#!/bin/bash
. Load

function GetJson()
{
    export Program=Curl
    export accessToken=$(cat /LocalSecrets/GitHubAccessToken)
    if [[ $Program == Curl ]]; then
        export Response=$(curl --silent -H "Authorization: token $accessToken" "https://api.github.com/orgs/$Organization/repos?per_page=100&page=$1")
    else
        wget -q -d -S --header="Authorization: token $accessToken" https://api.github.com/orgs/$Organization/repos?per_page=100&page=$1 -O /Temp/RepositoriesJson
        Divide
        Error "Got the response"
        Divide
        export Response=$(cat /Temp/RepositoriesJson)
    fi
}

function LoopAndClone()
{
    echo $Response
    echo $Response | jq -r ".[].name" | 
    {
        while read -r name ; do
            (git clone git@github.com:$Organization/$name) &
            # if [[ "$name" == *Api ]] || [[ "$name" == *Panel ]] || [[ "$name" == Site ]] || [[ "$name" == Common ]] || [[ "$name" == Blog ]]; then
            #     git clone git@github.com:$Organization/$name
            # fi
        done
        wait
    }
}

Organization=$1

if [[ $Organization == "" ]]; then 
    Error 'Organization name is not provided';
    exit;
fi

Info "Organization: $Organization"

sudo mkdir -p /$Organization
if [[ $(ls -lah /$Organization | wc -l) == 3 ]]; then
    Info "Giving full permission to /$Organization"
    sudo chmod 777 /$Organization
fi

cd /$Organization

GetJson 1

if [[ $Response == *"Not Found"* ]]; then
    # Response=$(curl --silent -H "Authorization: token $accessToken" "https://api.github.com/repos/PaydarNode/$Organization")
    if [[ $Response == *"Not Found"* ]]; then
        Error $Response
    else
        cd /PaydarNode
        git clone git@github.com:PaydarNode/$Organization
    fi
else
    LoopAndClone
    GetJson 2
    LoopAndClone
fi

find /PaydarCore /PaydarNode -maxdepth 2  -type d -name ".git" 2>/dev/null | xargs sudo chmod -R 777

Safe

FixGit

Divide
Success "Cloned all"
Divide
