#!/bin/bash
. Load

if [[ $@ == "" ]]; then 
    Info "type the Commands in one line:"
    read -e Command
else
    Command=$@
fi

if [[ $Command == "" ]]; then 
    Error 'Command not found'
    exit
fi

find /PaydarNode/Deployment/Servers/ | grep "server1.*$" | awk -F'/' '{ print "root@", $5 }' | awk {'print $1$2'} > /Temp/Hosts
sudo chmod 777 /Temp/Hosts

# exclude servers without SSH
sed -i '/server103/d' /Temp/Hosts
sed -i '/server104/d' /Temp/Hosts

parallel-ssh -i -h /Temp/Hosts -t 0 "echo && $Command && echo && echo -----------------------------------------------------"

rm -rf /Temp/Hosts
