#!/bin/bash
. Load

Command=$1
if [[ $Command == "" ]]; then 
    Error 'Command not found, please enter a single and valid command'
    exit
fi

find /PaydarCore/Deployment/Servers/ | grep "server1.*$" | awk -F'/' '{ print "root@", $5 }' | awk {'print $1$2'} > /Temp/Hosts
sudo chmod 777 /Temp/Hosts

# exclude servers without SSH
sed -i '/server103/d' /Temp/Hosts
sed -i '/server104/d' /Temp/Hosts

parallel-ssh -i -h /Temp/Hosts -t 0 "echo && $Command && echo && echo -----------------------------------------------------"

rm -rf /Temp/Hosts
