#!/bin/bash
. Load

if [[ $@ == "" ]]; then 
    Info "type the Commands in one line:"
    read -e Command
else
    Command=$@
fi

if [[ $Command == "" ]]; then 
    Error 'Command not found'
    exit
fi

find /PaydarNode/Deployment/Servers/ | grep "server2.*$" | awk -F'/' '{ print "administrator@", $5 }' | awk {'print $1$2'} > /Temp/Hosts
sudo chmod 777 /Temp/Hosts

# exclude servers from list
sed -i '/server201/d' /Temp/Hosts

parallel-ssh -i -h /Temp/Hosts -t 0 "echo. && $Command && echo. && echo -----------------------------------------------------"

rm -rf /Temp/Hosts
