#!/bin/bash

. Load

TargetDomain=$1
if [[ $TargetDomain == "" ]]; then 
    Error 'Domain is not provided';
    exit;
fi

ServerPath=$(cat /PaydarCore/Deployment/Hosts/$1 2>/dev/null | grep ServerPath | cut -d ' ' -f2)
if [[ $ServerPath == "" ]]; then 
    Error 'ServerPath is not available in the Local Hosts';
    exit;
fi

ProjectPath=$(cat /PaydarCore/Deployment/Hosts/$1 2>/dev/null | grep ProjectPath | cut -d ' ' -f2)
if [[ $ProjectPath == "" ]]; then 
    Error 'ProjectPath is not available in the Local Hosts';
    exit;
fi

Protocol=$(cat /PaydarCore/Deployment/Hosts/$1 2>/dev/null | grep Protocol | cut -d ' ' -f2)
if [[ $Protocol == "" ]]; then 
    Protocol='http'
fi

Info Validating server path...
if [[ ! `ssh root@$TargetDomain test -f $ServerPath/$TargetDomain.conf && echo exists` ]] ; then
    Error "Nginx configuration is not created for $TargetDomain"
    exit
fi
Success "$ServerPath exists"
Divide

Info Validating nginx config on server...
if [[ ! `ssh root@$TargetDomain test -f /etc/nginx/conf.d/$TargetDomain.conf && echo exists` ]] ; then
    Error "Nginx is not configured for $TargetDomain"
    exit
fi
Success "$TargetDomain.conf exists"
Divide

cd $ProjectPath

Info "Building the project..."
Divide

Build

Info "Project build finished"
Divide

sudo chmod 777 /Build
cd /Build

export Hash=$(cat /Build/hash)

Info "Compressing the built output... for $ProjectPath"

cd /$ProjectPath
if IsSite; then
    cd /Build
    sudo zip -rq publish.zip .next public next.config.js next.js package.json
elif IsPanel; then
    cd /Build
    sudo zip -r publish.zip assets hash images index.html
elif IsApi; then
    cd /Build
    sudo zip publish.zip ./**
fi

Success '100% Done'
Info "Built output is compressed"

export TargetDomain=$TargetDomain
export ServerPath=$ServerPath
export ProjectPath=$ProjectPath
export Protocol=$Protocol
export ServerPort=$(ssh root@$TargetDomain "/PaydarCore/ServerLinux/Commands/Port $TargetDomain")

cd /$ProjectPath
if IsSite; then
    sudo envsubst < /PaydarCore/ServerLinux/DeployerTemplates/Site > /Build/$TargetDomain.deployer
elif IsPanel; then
    sudo envsubst < /PaydarCore/ServerLinux/DeployerTemplates/Panel > /Build/$TargetDomain.deployer
elif IsApi; then
    sudo envsubst < /PaydarCore/ServerLinux/DeployerTemplates/Api > /Build/$TargetDomain.deployer
fi

sudo envsubst < /PaydarCore/ServerLinux/Commands/TelemetryTemplate > /Build/$TargetDomain.telemetry

Divide
Info "Removing old deployment..."

ssh root@$TargetDomain "rm -rf $ServerPath/$TargetDomain.deployer $ServerPath/publish.zip"

Success '100% Done'
Info "Old deployment files deleted"

Divide
Info "Uploading started..."

scp /Build/$TargetDomain.deployer root@$TargetDomain:$ServerPath
scp /Build/$TargetDomain.telemetry root@$TargetDomain:$ServerPath
scp /Build/publish.zip root@$TargetDomain:$ServerPath

Success '100% Done'
Info "Project uploaded."

Divide
Info "Deploying the project..."

ssh root@$TargetDomain "chmod 777 $ServerPath/$TargetDomain.telemetry"
ssh root@$TargetDomain "chmod 777 $ServerPath/$TargetDomain.deployer"
ssh root@$TargetDomain "$ServerPath/$TargetDomain.deployer" &
