#!/bin/bash

. Load

TargetDomain=$1
if [[ $TargetDomain == "" ]]; then 
    Error 'Domain is not provided';
    exit;
fi

ServerPath=$(cat /LocalSecrets/Deployment/$1 2>/dev/null | grep ServerPath: | cut -d ' ' -f2)
if [[ $ServerPath == "" ]]; then 
    Error 'ServerPath is not available in the LocalSecrets';
    exit;
fi

ProjectPath=$(cat /LocalSecrets/Deployment/$1 2>/dev/null | grep ProjectPath: | cut -d ' ' -f2)
if [[ $ProjectPath == "" ]]; then 
    Error 'ProjectPath is not available in the LocalSecrets';
    exit;
fi

Info Validating nginx config on server...
if [[ ! `ssh root@server7.paydardata.com test -f /etc/nginx/conf.d/$TargetDomain.conf && echo exists` ]] ; then
    Error "$TargetDomain is not hosted on server"
    exit
fi
Success "$TargetDomain.conf exists"
Divide

Info Validating server path...
if [[ ! `ssh root@server7.paydardata.com test -d $ServerPath && echo exists` ]] ; then
    Error "$ServerPath directory not exist on server"
    exit
fi
Success "$ServerPath exists"
Divide

cd $ProjectPath

Info Building the project...
Divide

Build

Info Project build finished
Divide

cd /Build

Info Compressing the built output...

zip -rq publish.zip .next public next.config.js next.js package.json

Success '100% Done'
Info Built output is compressed

export TargetDomain=$TargetDomain
export ServerPath=$ServerPath
export ProjectPath=$ProjectPath
envsubst < /PaydarCore/ServerLinux/Commands/DeployerTemplate > /Build/$TargetDomain.deployer
envsubst < /PaydarCore/ServerLinux/Commands/TelemetryTemplate > /Build/$TargetDomain.telemetry

Divide
Info Removing old deployment...

ssh root@server7.paydardata.com "rm -rf $ServerPath/$TargetDomain.deployer $ServerPath/publish.zip"

Success '100% Done'
Info Old deployment files deleted
Divide

Info Uploading started...

chmod 777 /Build/$TargetDomain.deployer
chmod 777 /Build/$TargetDomain.telemetry
scp /Build/$TargetDomain.deployer root@server7.paydardata.com:$ServerPath
scp /Build/$TargetDomain.telemetry root@server7.paydardata.com:$ServerPath
scp /Build/publish.zip root@server7.paydardata.com:$ServerPath

Success '100% Done'
Info Project uploaded.
Divide

Info Deploying the project...

ssh root@server7.paydardata.com "chmod 777 $ServerPath/$TargetDomain.telemetry"
ssh root@server7.paydardata.com "chmod 777 $ServerPath/$TargetDomain.deployer"
ssh root@server7.paydardata.com "$ServerPath/$TargetDomain.deployer"
