#!/bin/bash

. Load

TargetDomain=$1
if [[ $TargetDomain == "" ]]; then 
    Error 'Domain is not provided';
    exit;
fi

Hostname=$(cat /PaydarCore/Deployment/Hosts/$1 2>/dev/null | grep Hostname: | cut -d ' ' -f2)
if [[ $Hostname == "" ]]; then 
    Error 'Hostname is not available in the Local Hosts';
    exit;
fi

ServerPath=$(cat /PaydarCore/Deployment/Hosts/$1 2>/dev/null | grep ServerPath: | cut -d ' ' -f2)
if [[ $ServerPath == "" ]]; then 
    Error 'ServerPath is not available in the Local Hosts';
    exit;
fi

ProjectPath=$(cat /PaydarCore/Deployment/Hosts/$1 2>/dev/null | grep ProjectPath: | cut -d ' ' -f2)
if [[ $ProjectPath == "" ]]; then 
    Error 'ProjectPath is not available in the Local Hosts';
    exit;
fi

IsSecure=$(cat /PaydarCore/Deployment/Hosts/$1 2>/dev/null | grep IsSecure: | cut -d ' ' -f2)
if [[ $IsSecure == "" ]]; then 
    IsSecure=0
fi

Info Validating nginx config on server...
if [[ ! `ssh root@$Hostname test -f /etc/nginx/conf.d/$TargetDomain.conf && echo exists` ]] ; then
    Error "$TargetDomain is not hosted on server"
    exit
fi
Success "$TargetDomain.conf exists"
Divide

Info Validating server path...
if [[ ! `ssh root@$Hostname test -d $ServerPath && echo exists` ]] ; then
    Error "$ServerPath directory not exist on server"
    exit
fi
Success "$ServerPath exists"
Divide

cd $ProjectPath

Info Building the project...
Divide

Build

Info Project build finished
Divide

cd /Build

export Hash=$(cat /Build/hash)

Info Compressing the built output...

zip -rq publish.zip .next public next.config.js next.js package.json

Success '100% Done'
Info Built output is compressed

export TargetDomain=$TargetDomain
export Hostname=$Hostname
export ServerPath=$ServerPath
export ProjectPath=$ProjectPath
export IsSecure=$IsSecure
export ServerPort=$(ssh root@$Hostname "/PaydarCore/ServerLinux/Commands/Port $TargetDomain")
envsubst < /PaydarCore/ServerLinux/Commands/DeployerTemplate > /Build/$TargetDomain.deployer
envsubst < /PaydarCore/ServerLinux/Commands/TelemetryTemplate > /Build/$TargetDomain.telemetry

Divide
Info Removing old deployment...

ssh root@$Hostname "rm -rf $ServerPath/$TargetDomain.deployer $ServerPath/publish.zip"

Success '100% Done'
Info Old deployment files deleted

Divide
Info Uploading started...

scp /Build/$TargetDomain.deployer root@$Hostname:$ServerPath
scp /Build/$TargetDomain.telemetry root@$Hostname:$ServerPath
scp /Build/publish.zip root@$Hostname:$ServerPath

Success '100% Done'
Info Project uploaded.

Divide
Info Deploying the project...

ssh root@$Hostname "chmod 777 $ServerPath/$TargetDomain.telemetry"
ssh root@$Hostname "chmod 777 $ServerPath/$TargetDomain.deployer"
ssh root@$Hostname "$ServerPath/$TargetDomain.deployer" &
