#!/bin/bash

. Load

sudo echo ""

ImageName=$1

export UsbRoot=/media/$USER/Docker
export Temp=/Temp/Docker

if [ ! -d $UsbRoot ]; then
    Error "No USB memory is found"
    exit
fi

sudo mkdir -p $Temp
sudo chmod -R 777 $Temp

# Warning "Use 'progress' command to see the progress!"

cd $Temp

function SaveApi()
{
    Info "Saving paydar/api ..."
    docker save paydar/api > $Temp/PaydarApi
    Info "Zipping paydar/api ..."
    zip PaydarApi.zip PaydarApi 1>/dev/null
    Info "Copying paydar/api to USB ..."
    cp $Temp/PaydarApi.zip $UsbRoot
    Success paydar/api
}

function SavePanel()
{
    Info "Saving paydar/panel ..."
    docker save paydar/panel > $Temp/PaydarPanel
    Info "Zipping paydar/panel ..."
    zip PaydarPanel.zip PaydarPanel 1>/dev/null
    Info "Copying paydar/panel to USB ..."
    cp $Temp/PaydarPanel.zip $UsbRoot
    Success paydar/panel
}

function SaveSite()
{
    Info "Saving paydar/site ..."
    docker save paydar/site > $Temp/PaydarSite
    Info "Zipping paydar/site ..."
    zip PaydarSite.zip PaydarSite 1>/dev/null
    Info "Copying paydar/site to USB ..."
    cp $Temp/PaydarSite.zip $UsbRoot
    Success paydar/site
}

function SaveSql()
{
    Info "Saving paydar/sql ..."
    docker save paydar/sql > $Temp/PaydarSql
    Info "Zipping paydar/sql ..."
    zip PaydarSql.zip PaydarSql 1>/dev/null
    Info "Copying paydar/sql to USB ..."
    cp $Temp/PaydarSql.zip $UsbRoot
    Success paydar/sql
}

Start

if [[ $ImageName == "" ]]; then

    SaveApi

    Divide

    SavePanel

    Divide

    SaveSite

    Divide

    SaveSql

else

    if [[ $ImageName == "paydar/api" ]]; then
        SaveApi
    fi
    if [[ $ImageName == "paydar/panel" ]]; then
        SavePanel
    fi
    if [[ $ImageName == "paydar/site" ]]; then
        SaveSite
    fi
    if [[ $ImageName == "paydar/sql" ]]; then
        SaveSql
    fi
fi

Stop
