#!/bin/bash

if [ -d /media/$USER/Repository/Docker ]; then
  for DockerImageFile in `find /media/$USER/Repository/Docker -type f -print`; do
    docker load < $DockerImageFile;
  done
else
  docker pull paydar/api
  docker pull paydar/database
  docker pull paydar/panel
  docker pull paydar/site
fi
