#!/bin/bash

. Load

sudo echo ""

ImageName=$1

export UsbRoot=/media/$USER/Docker
export Temp=/Temp/Docker

if [ ! -d $UsbRoot ]; then
    Error "No USB memory is found"
    exit
fi

sudo rm -rf $Temp
sudo mkdir -p $Temp
sudo chmod -R 777 $Temp

cd $Temp

function LoadApi()
{
    Info "Copying paydar/api from USB ..."
    cp $UsbRoot/PaydarApi.zip $Temp
    Info "Unzipping paydar/api ..."
    unzip PaydarApi.zip 1>/dev/null
    Info "Loading paydar/api ..."
    docker load < $Temp/PaydarApi
    Success paydar/api
}

function LoadPanel()
{
    Info "Copying paydar/panel from USB ..."
    cp $UsbRoot/PaydarPanel.zip $Temp
    Info "Unzipping paydar/panel ..."
    unzip PaydarPanel.zip 1>/dev/null
    Info "Loading paydar/panel ..."
    docker load < $Temp/PaydarPanel
    Success paydar/panel
}

function LoadSite()
{
    Info "Copying paydar/site from USB ..."
    cp $UsbRoot/PaydarSite.zip $Temp
    Info "Unzipping paydar/site ..."
    unzip PaydarSite.zip 1>/dev/null
    Info "Loading paydar/site ..."
    docker load < $Temp/PaydarSite
    Success paydar/site
}

function LoadDatabase()
{
    Info "Copying paydar/database from USB ..."
    cp $UsbRoot/PaydarDatabase.zip $Temp
    Info "Unzipping paydar/database ..."
    unzip PaydarDatabase.zip 1>/dev/null
    Info "Loading paydar/database ..."
    docker load < $Temp/PaydarDatabase
    Success paydar/database
}

Start

if [[ $ImageName == "" ]]; then

    LoadApi

    Divide

    LoadPanel

    Divide

    LoadSite

    Divide

    LoadDatabase

else

    if [[ $ImageName == "paydar/api" ]]; then
        LoadApi
    fi
    if [[ $ImageName == "paydar/panel" ]]; then
        LoadPanel
    fi
    if [[ $ImageName == "paydar/site" ]]; then
        LoadSite
    fi
    if [[ $ImageName == "paydar/database" ]]; then
        LoadDatabase
    fi
fi

Stop
