#!/bin/bash

. Load

sudo echo

ImageName=$1

export UsbRoot=/media/$USER/Docker
export Temp=/Temp/Docker

if [ ! -d $UsbRoot ]; then
    Error "No USB memory is found"
    exit
fi

sudo mkdir -p $Temp
sudo chmod -R 777 $Temp

# Warning "Use 'progress' command to see the progress!"

cd $Temp

function SaveApi()
{
    Info "Saving paydar/api ..."
    docker save paydar/api > $Temp/PaydarApi
    Info "Zipping paydar/api ..."
    zip PaydarApi.zip PaydarApi 1>/dev/null
    Info "Copying paydar/api to USB ..."
    cp $Temp/PaydarApi.zip $UsbRoot
    Success paydar/api
}

function SavePanel()
{
    Info "Saving paydar/panel ..."
    docker save paydar/panel > $Temp/PaydarPanel
    Info "Zipping paydar/panel ..."
    zip PaydarPanel.zip PaydarPanel 1>/dev/null
    Info "Copying paydar/panel to USB ..."
    cp $Temp/PaydarPanel.zip $UsbRoot
    Success paydar/panel
}

function SaveSite()
{
    Info "Saving paydar/site ..."
    docker save paydar/site > $Temp/PaydarSite
    Info "Zipping paydar/site ..."
    zip PaydarSite.zip PaydarSite 1>/dev/null
    Info "Copying paydar/site to USB ..."
    cp $Temp/PaydarSite.zip $UsbRoot
    Success paydar/site
}

function SaveDatabase()
{
    Info "Saving paydar/database ..."
    docker save paydar/database > $Temp/PaydarDatabase
    Info "Zipping paydar/database ..."
    zip PaydarDatabase.zip PaydarDatabase 1>/dev/null
    Info "Copying paydar/database to USB ..."
    cp $Temp/PaydarDatabase.zip $UsbRoot
    Success paydar/database
}

function SaveImage()
{
    FileName=${ImageName/\//-}
    Info "Saving $ImageName ..."
    docker save $ImageName > $Temp/$FileName
    Info "Zipping $ImageName ..."
    zip $FileName.zip $FileName 1>/dev/null
    Info "Copying $ImageName to USB ..."
    cp $Temp/$FileName.zip $UsbRoot
    Success $ImageName
}

Start

if [[ $ImageName == "" ]]; then

    SaveApi

    Divide

    SavePanel

    Divide

    SaveSite

    Divide

    SaveDatabase

else

    if [[ $ImageName == "paydar/api" ]]; then
        SaveApi
    elif [[ $ImageName == "paydar/panel" ]]; then
        SavePanel
    elif [[ $ImageName == "paydar/site" ]]; then
        SaveSite
    elif [[ $ImageName == "paydar/database" ]]; then
        SaveDatabase
    else
        SaveImage
    fi
fi

Stop

rm -rf $Temp
