#!/bin/bash

. Load

echo
Warning 'All of your local changes will be deleted permanentaly.'
Warning 'Are you sure you want to reset? (y,n)'
read Consent

if [ $Consent != 'y' ]; then
    exit;
fi

FindGits |
{
    while read gitFolder; do
        parent=$(dirname $gitFolder);
        echo "";
        echo $parent;
        (git -C $parent reset --hard && git -C $parent clean -fxd && echo "Reset $parent is done") &
    done 
    wait
}
Divide
Success "Reset all"
Divide
