#!/bin/bash

red=`tput setaf 1`
green=`tput setaf 2`
cyan=`tput setaf 6`
magenta=`tput setaf 5`
yellow=`tput setaf 3`
reset=`tput sgr0`

Check="\xE2\x9C\x94"
Cross="\xE2\x9C\x96"

function Success()
{
    echo -e "${green}$*${reset}" | column -t -s ';'
}

function Info()
{
    echo "${cyan}$*${reset}"
}

function Warning()
{
    echo "${yellow}$*${reset}"
}

function Error()
{
    echo -e "${red}$*${reset}" | column -t -s ';'
}

function Divide()
{
    echo
    echo "${magenta}----------${reset}"
    echo
}

function CreateFilesAndFolders()
{
    sudo mkdir -p /LocalSecrets
    sudo touch /LocalSecrets/GitHubAccessToken
    sudo touch /LocalSecrets/GitHubUserName
    sudo touch /LocalSecrets/GitHubUserEmail
    sudo touch /LocalSecrets/Vpn

    sudo chmod -R 777 /LocalSecrets
}

function VpnAccount()
{
    if [[ $(cat /LocalSecrets/Vpn | wc -c) < 2 ]]; then
        Divide
        Info 'Please give me the VPN server address, for example: yourserver:443'
        read Server
        Divide
        Info 'Please enter your VPN username, for example: paydar'
        read Username
        Divide
        Info 'Please enter your VPN password, for example: p@yd@r'
        read Password
        echo "Server=$Server" > /LocalSecrets/Vpn
        echo "Username=$Username" >> /LocalSecrets/Vpn
        echo "Password=$Password" >> /LocalSecrets/Vpn
        echo 'printf "$Username\n$Password" | sudo openconnect $Server' >> /LocalSecrets/Vpn
        sudo chmod 777 /LocalSecrets/Vpn
    fi
}

function GitHubAccessToken()
{
    if [[ $(cat /LocalSecrets/GitHubAccessToken | wc -c) < 2 ]]; then
        Divide
        Info Please enter your GitHubAccessToken
        read GitHubAccessToken
        Divide
        echo "$GitHubAccessToken" > /LocalSecrets/GitHubAccessToken
        sudo chmod 777 /LocalSecrets/GitHubAccessToken
    fi

    if [[ $(cat /LocalSecrets/GitHubAccessToken | wc -c) < 40 ]]; then
        Error "GitHubAccesstoken;$Cross"
        Error "\tInvalid content in GitHubAccessToken, make sure save your GitHub PersonalAccessToken is valid"
        exit;
    fi
}

function GitHubUserName()
{
    if [[ $(cat /LocalSecrets/GitHubUserName | wc -c) < 2 ]]; then
        Divide
        Info Please enter your GitHubUserName
        read GitHubUserName
        Divide
        echo "$GitHubUserName" > /LocalSecrets/GitHubUserName
        sudo chmod 777 /LocalSecrets/GitHubUserName
    fi
}

function GitHubUserEmail()
{
    if [[ $(cat /LocalSecrets/GitHubUserEmail | wc -c) < 2 ]]; then
        Divide
        Info Please enter your GitHubUserEmail
        read GitHubUserEmail
        Divide
        echo "$GitHubUserEmail" > /LocalSecrets/GitHubUserEmail
        sudo chmod 777 /LocalSecrets/GitHubUserEmail
    fi
}

Divide
Info "Paydar Holding Infra Authentication"
Divide

CreateFilesAndFolders
VpnAccount
GitHubAccessToken
GitHubUserName
GitHubUserEmail
