#!/bin/bash

. Load

sudo ""

clear

Host=$1

if [[ $Host == "" ]]; then
    if [[ -f Host ]]; then
        Host=$(cat Host)
    fi
fi
echo $Host
exit

shift
for i in "$@"; do
    Previous=$i
done

http --follow --verbose GET https://$Host/account/loginViaGet?username=superadmin&password=100 "$@"
