#!/bin/bash

red=`tput setaf 1`
green=`tput setaf 2`
cyan=`tput setaf 6`
magenta=`tput setaf 5`
yellow=`tput setaf 3`
reset=`tput sgr0`

Check="\xE2\x9C\x94"
Cross="\xE2\x9C\x96"

function Success()
{
    echo -e "${green}$*${reset}" | column -t -s ';'
}

function Info()
{
    echo "${cyan}$*${reset}"
}

function Warning()
{
    echo "${yellow}$*${reset}"
}

function Error()
{
    echo -e "${red}$*${reset}" | column -t -s ';'
}

function Divide()
{
    echo ""
    echo "${magenta}----------${reset}"
    echo ""
}

function CreateFilesAndFolders()
{
    sudo mkdir -p /LocalSecrets
    sudo touch /LocalSecrets/GitHubAccessToken
    sudo touch /LocalSecrets/GitHubUserName
    sudo touch /LocalSecrets/GitHubUserEmail
    sudo touch /LocalSecrets/Vpn

    sudo chmod -R 777 /LocalSecrets
}

function GitHubAccessToken()
{
    if [[ $(cat /LocalSecrets/GitHubAccessToken | wc -c) < 40 ]]; then
        Error "GitHubAccesstoken;$Cross"
        Error "\tInvalid content in GitHubAccessToken, make sure save your GitHub PersonalAccessToken is valid"
        exit;
    fi
}

function GitHubUserName()
{
    if [[ $(cat /LocalSecrets/GitHubUserName | wc -c) < 1 ]]; then
        Divide
        Info Please enter your GitHubUserName
        Divide
        read GitHubUserName
        Divide
        echo "$GitHubUserName" | sudo tee -a /LocalSecrets/GitHubUserName > /dev/null
        sudo chmod 777 /LocalSecrets/GitHubUserName
    fi
}

function GitHubUserEmail()
{
    if [[ $(cat /LocalSecrets/GitHubUserEmail | wc -c) < 1 ]]; then
        Divide
        Info Please enter your GitHubUserEmail
        Divide
        read GitHubUserEmail
        Divide
        echo "$GitHubUserEmail" | sudo tee -a /LocalSecrets/GitHubUserEmail > /dev/null
        sudo chmod 777 /LocalSecrets/GitHubUserEmail
    fi
}

Divide
Info "Paydar Holding Athentication"
Divide

CreateFilesAndFolders
GitHubAccessToken
GitHubUserName
GitHubUserEmail
