#!/bin/bash

. Load

sudo ""

clear

Url=$1
HasFile=false

shift
for i in "$@"; do
    Previous=$i
    if [[ $i == *@* ]]; then
        HasFile=true
    fi
done

if [[ $HasFile == true ]]; then
    http -f --follow --verbose POST https://$Url "$@"
else
    http --follow --verbose POST https://$Url "$@"
fi

