#!/bin/bash

. Load

FindGits | 
{
    while read gitFolder; do
        parent=$(dirname $gitFolder);
        echo "";
        Info $parent;
        (git -C $parent pull; Success "Got $parent") &
    done 
    wait
}
Divide
Success "Got all"
Divide

Safe
