#!/bin/bash

. Load

find /PaydarCore /PaydarNode -maxdepth 2  -type d -name .git 2>/dev/null | 
{
    while read gitFolder; do
        parent=$(dirname $gitFolder);
        echo "";
        Info $parent;
        (sudo git -C $parent pull; Success "Got $parent") &
    done 
    wait
}
Divide
Success "Got all"
Divide