#!/bin/bash

. Load

FindGits | 
{
    while read gitFolder; do
        parent=$(dirname $gitFolder);
        echo "";
        Info $parent;
        (git -C $parent pull; Success "Got $parent") &
    done 
    wait
}
Divide
Success "Got all"
Divide

# Tempurary commands
sudo chmod 777 ~/.gitconfig
git config --global core.filemode false
Safe
FixGit
