#!/bin/bash

sudo chmod 777 /etc/docker

sudo echo "{" > /etc/docker/daemon.json
sudo echo "  \"registry-mirrors\": [\"https://docker.iranserver.com\"]" >> /etc/docker/daemon.json
sudo echo "}" >> /etc/docker/daemon.json

sudo systemctl daemon-reload
sudo systemctl restart docker

# https://mirror.iranserver.com/docker/