#!/bin/bash

. Load

Info 'Setting all git repositories to safe ...'

FindGits | 
{
    while read gitFolder; do
        parent=$(dirname $gitFolder);
        git config --global --add safe.directory $parent
        git -C $parent config core.filemode false
    done
    wait
}
Divide
Success "All git repositories are set to be safe"
Divide

# Tempurary commands
Info 'Ignoring file mode for all git repositories...'
Divide
sudo chmod 777 ~/.gitconfig
git config --global core.filemode false
Success 'file mode of all git repositories falsed'
Divide
