#!/bin/bash

. Load

Info 'Setting all git repositories to safe ...'

FindGits | 
{
    while read gitFolder; do
        parent=$(dirname $gitFolder);
        git config --global --add safe.directory $parent
    done
    wait
}
Divide
Success "All git repositories are set to be safe"
Divide
