#!/bin/bash

. Load

TargetDomain=$1
if [[ $TargetDomain == "" ]]; then 
    Error 'Domain is not provided'
    exit
fi

getent hosts $TargetDomain > /dev/null

Ip=$(getent hosts $TargetDomain | awk '{ print $1 }')
if [[ $Ip == "" ]]; then 
    Error 'Cannot find IP Address'
    echo
    exit
fi

HostServer=$(grep $Ip /PaydarCore/Deployment/Servers/* | cut -d: -f1  | cut -d/ -f5)
if [[ $HostServer == "" ]]; then 
    Error 'Cannot find server'
    Warning 'make sure this domain hosted by Paydar and exist in Deployment/Servers'
    echo
    exit
fi


Info HostServer:
echo $HostServer
Info Ip:
echo $Ip
echo
