#!/bin/bash

. Load

ForBuild=$1

sudo echo ""

clear

Info "Paydar Setup"

if [ $PWD = '/' ]; then
    Error "You are in the root directory. Run Setup from inside a project's directory";
    exit;
fi

if ! (IsRazor || IsNext || IsReact || IsDotNet); then
    Error "Unknown project";
    exit;
fi

Extract
SetPaths
CreateTempDirectories &
GetRandomPort
GetHost
CreateCertificate
SetupNginx
SetupLocalDns
CleanDocker
CopyGitIgnore

sudo chmod -R 777 /$Organization/$Repository

export ComposePath=/Temp/$Organization/$Repository/$Project/DockerCompose.yml
sudo mkdir -p $(dirname $ComposePath)

if IsRazor $1; then
    SetupRazor;
elif IsNext $1; then
    SetupNext;
elif IsReact $1; then
    SetupReact;
elif IsDotNet $1; then
    SetupDotNet
else
    Warning "Unknown project"
fi
if [[ $ForBuild == "" ]]; then
    if IsDotNet $1 && [[ $Repository != "Storage" ]]; then
        cd /PaydarNode/Storage/Api
        Setup
    fi
    if [[ $Repository == "Storage" ]]; then
        if [[ $(docker container ls | grep StorageApi ) ]]; then
            Info "Storage container is running"
        else
            docker-compose -p "${Repository}_${Project}" -f $ComposePath up --remove-orphans -d
        fi
    else
        docker-compose -p "${Repository}_${Project}" -f $ComposePath up --remove-orphans
    fi
else
    docker-compose -p "${Repository}_${Project}" -f $ComposePath up --remove-orphans -d
fi
