#!/bin/bash

. Load

Domain=$1

if [[ $Domain == "" ]]; then
    Divide
    Error Ssh to where? Please provide the domain name
    Divide
fi

# if ssh -o IdentitiesOnly=yes -o BatchMode=yes -i ~/.ssh/id_ed25519.pub -q root@$Domain exit; then
#     echo "Connection succesful"
# else
#     echo "Connection not succesful"
# fi

ssh -A root@$Domain

function HowTo()
{
    cd ~/.ssh # ssh-keygen would create the key pair in the current directory
    ssh-keygen # to create a key pair on your local, named ~/.ssh/key_name
    ssh-copy-id -i ~/.ssh/key_name root@domain # to copy the id to the server
    ssh root@domain # to login without password
}
