#!/bin/bash

. Load

Domain=$1

if [[ $Domain == "" ]]; then
    Divide
    Error Ssh to where? Please provide the domain name
    Divide
fi

# if ssh -o IdentitiesOnly=yes -o BatchMode=yes -i ~/.ssh/id_ed25519.pub -q root@$Domain exit; then
#     echo "Connection succesful"
# else
#     echo "Connection not succesful"
# fi

Server $Domain
Divide
Ip=$(getent hosts $Domain | awk '{ print $1 }')
HostServer=$(grep $Ip /PaydarCore/Deployment/Servers/* | cut -d: -f1  | cut -d/ -f5)
FirstNumber=$(echo $HostServer | cut -c 7)

if [[ $FirstNumber == 1 ]]; then

    Info Linux Server
    ServerPath=$(cat /PaydarCore/Deployment/Hosts/$1 2>/dev/null | grep ServerPath | awk '{print $2}')
    if [[ $ServerPath != "" ]]; then 
        ssh -A root@$Domain -t "cd $ServerPath; bash --login"
        exit;
    fi
    ssh -A root@$Domain

elif [[ $FirstNumber == 2 ]]; then

    Info Windows Server
    ssh -A administrator@$Domain

else
    Error Unknown OS
fi

function HowTo()
{
    cd ~/.ssh # ssh-keygen would create the key pair in the current directory
    ssh-keygen # to create a key pair on your local, named ~/.ssh/key_name
    ssh-copy-id -i ~/.ssh/key_name root@domain # to copy the id to the server
    ssh root@domain # to login without password
}
