#!/bin/bash

. Load

echo

# Start

# FindGits | 
# {
#     while read gitFolder; do
#         (
#             parent=$(dirname $gitFolder);
#             if [[ $? == 128 ]]; then
#                 Error "Git is broken in $parent"
#             else
# 	        Status=$(git -C $parent status)
#                 if [[ `git -C $parent status --porcelain` ]]; then
#                     Info $parent;
#                     git -C $parent status --porcelain
#                     if [ -d /PaydarCore/Policies ]; then
#                         /PaydarCore/Policies/Run.sh $parent
#                     fi
#                     Divide
#                 elif [[ $Status == *ahead* ]]; then
#                     Warning "Push $parent";
#                     Divide
#                 elif [[ $Status == *diverged* ]]; then
#                     Warning "Sync $parent";
#                     Divide
#                 fi
#             fi
#         ) &
#     done
#     wait
# }
# Stop

Divide

Start
function Check() 
{
    . /PaydarCore/Scripts/Message
    gitFolder="$1"
    parent=$(dirname $gitFolder);
    Status=$(git -C $parent status)
    if [[ $Status == *Changes* ]] || [[ $Status == *Untracked* ]]; then
        Info $parent;
        git -C $parent status --porcelain
        Divide
    elif [[ $Status == *ahead* ]]; then
        Warning "Push $parent";
        Divide
    elif [[ $Status == *diverged* ]]; then
        Warning "Sync $parent";
        Divide
    fi
}
export -f Check
FindGits | parallel -j0 Check
Stop
Divide

# https://stackoverflow.com/questions/9612090/how-to-loop-through-file-names-returned-by-find
