#!/bin/bash

. Load

echo

Start

FindGits | 
{
    while read gitFolder; do
        parent=$(dirname $gitFolder);
        (
            git -C $parent status 1>/dev/null 2>/dev/null
            if [[ $? == 128 ]]; then
                Error "Git is broken in $parent"
            else
                if [[ `git -C $parent status --porcelain` ]]; then
                    Info $parent;
                    git -C $parent status --porcelain
                    if [ -d /PaydarCore/Policies ]; then
                        /PaydarCore/Policies/Run.sh $parent
                    fi
                    Divide
                elif [[ $(git -C $parent status | grep ahead) ]]; then
                    Warning "Push $parent";
                    Divide
                elif [[ $(git -C $parent status | grep diverged) ]]; then
                    Warning "Sync $parent";
                    Divide
                fi
            fi
        ) &
    done
    wait
}

Stop
Divide

# https://stackoverflow.com/questions/9612090/how-to-loop-through-file-names-returned-by-find
