#!/bin/sh

echo "Get latest versions from internet"
sudo apt-get update
sudo apt-get -u upgrade

echo "Create archive folder on usb stick"
mkdir /media/$USER/Repository
sudo chmod -R 777 /media/$USER/Repository

echo "Copy files from cache to repository"
cp /var/cache/apt/archives/*.deb /media/$USER/Repository

echo "Change to Repository Directory"
cd /media/$USER/Repository
sudo mkdir binary
sudo chmod -R 777 binary

echo "Make Packages.gz file for synaptic"
sudo apt-get install build-essential
sudo dpkg-scanpackages binary /dev/null | gzip -9c > Packages.gz

echo "Repository is up to date"

# Edit your /etc/apt/sources.list file.
# sudo gedit /etc/apt/sources.list
# And insert this on a new line (preferably the first):
# deb [trusted=yes] file:/media/$USER/Repository/ ./
